name: YouTube Data Collection

on:
  schedule:
    - cron: '0 14 * * *'  # 9 AM EST
    - cron: '0 2 * * *'   # 9 PM EST
  workflow_dispatch:  # Enables manual trigger

permissions:
  contents: write  # Grant write permissions to GITHUB_TOKEN

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run data collection
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        cd data_collection
        python collect.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/youtube_data.db
        git diff --quiet && git diff --staged --quiet || (git commit -m "Data collection: $(date -u)" && git push)